### ISSUE TITLE
Documentation: Application Identity and Authorization

### ISSUE THREAD

**Issue by AlexShkunov** [ibm-cloud-security/appid-serversdk-nodejs#129]
https://github.com/ibm-cloud-security/appid-serversdk-nodejs#application-identity-and-authorization

Few issues about App to App concept and Snippet docs

- Snippet does not demonstrate where "config" object is used
- variable declared with capital T, but called with lower t 
(const TokenManager /// tokenManager.getApplicationIdentityToken() )
- usage of not declared "res" variable
- attempt to run the snippet anyway results in 
TypeError: TokenManager.getApplicationIdentityToken is not a function

**Comment by icemann92** [comment]
Thanks for pointing it out. Readme has been updated!
