### ISSUE TITLE
logout doesn't logout?

### ISSUE THREAD

**Issue by ScottChapman** [ibm-cloud-security/appid-serversdk-nodejs#134]
I'm following the documentation here, and I have a logout endpoint exactly like what is in the readme. However when it redirects to my root again, it still shows me as authenticated...

**Comment by vykimo** [comment]
Same issue with ibmcloud-appid 6.0.1

**Comment by vykimo** [comment]
Solution found ! You've to add 
```
 fetch("/auth/logout", {
        credentials: "include"
      })
```
when you call the route

**Comment by hardt-rmt** [comment]
Logout works
