### ISSUE TITLE
WebAppStrategy should support `verify` callback in constructor

### ISSUE THREAD

**Issue by swgraham** [ibm-cloud-security/appid-serversdk-nodejs#146]
WebAppStrategy should support `verify` callback in constructor

Most (if not all) strategies supported in passport strategies support a `verify` callback in the constructor, for example in https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js the constructor looks like:
```
* @constructor
 * @param {Object} options
 * @param {Function} verify
 * @api public
 */
function OAuth2Strategy(options, verify) {
  if (typeof options == 'function') {
    verify = options;
    options = undefined;
  }
```

This is important because the passport documentation specifies the `verify` callback be used to 'store' or persist user association(from http://www.passportjs.org/docs/authenticate/) : 
>Verify Callback
>This example introduces an important concept. Strategies require what is known as a verify callback. >The purpose of a verify callback is to find the user that possesses a set of credentials.

>When Passport authenticates a request, it parses the credentials contained in the request. It then >invokes the verify callback with those credentials as arguments, in this case username and password. >If the credentials are valid, the verify callback invokes done to supply Passport with the user that >authenticated.

This is impacting me because other middleware/wrappers like: https://github.com/strongloop/loopback-component-passport require the `verify` callback to persist users into databases or look them up and validate in your user model.

**Comment by hardt-rmt** [comment]
A verify callback has been added to the WebAppStrategy
