### ISSUE TITLE
CircularJSON is in maintenance only, flatted is its successor.

### ISSUE THREAD

**Issue by vinodtelang** [ibm-cloud-security/appid-serversdk-nodejs#153]
Hello Team,

Have noticed the following warning while trying to install the ibmcloud-appid using the command "npm install --save ibmcloud-appid"

npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

Kindly suggest here.

**Comment by hardt-rmt** [comment]
This had been fixed, thanks.
