### ISSUE TITLE
Module not found: Can't resolve 'cluster' (React)

### ISSUE THREAD

**Issue by brandonwarech** [ibm-cloud-security/appid-serversdk-nodejs#157]
![image](https://user-images.githubusercontent.com/34520013/59810729-3dd71400-92cc-11e9-9dfe-35ea079ffb33.png)

**Comment by mohan-mac** [comment]
Can you add your App.js code.

**Comment by TalAviel** [comment]
This is a server-side SDK, you can not use it in as a front-end dependency. 

You can read more about it on our docs:
- Single page applications: https://cloud.ibm.com/docs/services/appid?topic=appid-single-page
- Webapps: https://cloud.ibm.com/docs/services/appid?topic=appid-web-apps
