### ISSUE TITLE
Setting cookie.sameSite to true in express-session causes appID to fail

### ISSUE THREAD

**Issue by davydnorris** [ibm-cloud-security/appid-serversdk-nodejs#170]
Have been chasing down a failing appID implementation, and wanted to make a note here for others.

I had tightened up security for my express session, and had the following configuration:

```
const session_opts = {
	secret: 'keyboardcat',
	store: store,
	resave: true,
	saveUninitialized: true,
	proxy: true,
	cookie: {
		secure: true,
		sameSite: true,
		httpOnly: true,
		maxAge: 600000000
	}
};

const strategy_opts = {
	tenantId: appid_info.tenantId,
	clientId: appid_info.clientId,
	secret: appid_info.secret,
	oauthServerUrl: appid_info.oAuthServerUrl,
	redirectUri: env.url + '/callback'
};

module.exports = (app) => {
	app.use(session(session_opts));
	app.use(passport.initialize());
	app.use(passport.session());

	passport.use(new WebAppStrategy(strategy_opts));
...
```

The implementation was correctly redirecting to the appID login page, and then redirecting back to the callback page with the tokens, but then was silently failing to retrieve the tokens and complete the authentication, and also failing to then redirect to the page indicated in the `successRedirect` parameter.

I had turned on all logging levels and there was nothing that pointed to the fact the authentication wasn't completing, however logging req.session showed that none of the appID properties were being set.

I finally pulled the example application and got it running and gradually added my changes until I found that it was the sameSite parameter. My configuration was based on a recommendation for reducing the likelihood of CSRF attacks. I haven't yet tried using `sameSite: lax`, but just be aware that using `sameSite: true` or `sameSite: strict` will cause appID to silently fail.

Perhaps more logging could be added to catch this problem where the required cookies are not being found?

**Comment by davydnorris** [comment]
I've just checked and using `sameSite: 'lax'` results in a successful log in - this is a step up from not using the sameSite parameter at all.

**Comment by hardt-rmt** [comment]
Also, if you plan on explicitly stating cookie usage with "sameSite" attribute, you can set the value to "Lax" to safely maintain cookie preferences across sites or "None" to have the cookie sent in all context but if you use "None", make sure to specify "Secure" to require a secure context in all cases.
