### ISSUE TITLE
How can I delete a APP ID user

### ISSUE THREAD

**Issue by neerajkaushik** [ibm-cloud-security/appid-serversdk-nodejs#172]

**Comment by rotembr** [comment]
Hi @neerajkaushik 
Deleting App ID user is not supported in the App ID Node.js SDK.
You can delete the user using the App ID dashboard, 
or if you need to perform it in run-time you can use the App ID APIs for deleting a user,
for Cloud Directory users use: 
https://cloud.ibm.com/apidocs/app-id/management#delete-cloud-directory-user-and-profile
for all other users use: 
https://cloud.ibm.com/apidocs/app-id/management#delete-user
