### ISSUE TITLE
Custom login screen with SelfServiceManager

### ISSUE THREAD

**Issue by azihassan** [ibm-cloud-security/appid-serversdk-nodejs#173]
The readme file mentions that it is possible to use SelfServiceManager to login with a custom login screen :

>Use the self service manager when you want to control the UI for the sign-in, sign-up, forgot password, changeDetail and change password flows.

However, it doesn't seem to expose a signIn method or anything of the sort. Is this expected behavior ? If so, is there another way that would allow us to use a custom login form with App ID ?

Thanks in advance.

**Comment by rotembr** [comment]
Hi @azihassan ,
In order to sign-in Cloud directory users you can pass the username and password directly to the  WebAppStrategy.
https://github.com/ibm-cloud-security/appid-serversdk-nodejs#login-using-resource-owner-password-flow

This is the reason why there is no sign-in option in the SelfServiceManager.

**Comment by azihassan** [comment]
Hello @rotembr

Thanks for the quick reply, I appreciate it. I just tried WebAppStrategy this morning and it does in fact allow me to use my own login screen. I suggest that the "sign-in" mention be removed from the section that addresses SelfServiceManager to avoid confusion, I can submit a PR if you want.

I noticed that the proposed solution follows the resource owner password flow, and I'm considering it for our SPA. The default IBM App ID form follows the authorization code flow with PKCE, which seems to be the current best practice to follow as far as SPAs are concerned.  I would like to adopt it, but the login form widget offered by App ID isn't customizable enough for our needs. Is it possible to host our own login form at App ID and use it with the authorization code flow ?

**Comment by rotembr** [comment]
Hi @azihassan 
You can use the WebAppStrategy to login user using your own login page, you will only need to pass the form username and password.
Go ahead and open a PR we will consider it.

Unfortunately you can't host your own login screen at App ID.
If you need more customization to the login screen than what there is, you will have to build your own login page and use the resource owner password flow to login user.
Check our docs: https://cloud.ibm.com/docs/services/appid?topic=appid-branded
and this 2 blogs might help:
https://www.ibm.com/cloud/blog/use-branded-ui-user-sign-app-id
https://www.ibm.com/cloud/blog/use-ui-flows-user-sign-sign-app-id

**Comment by azihassan** [comment]
Thanks again, you've been very helpful. I now consider this problem to be solved.
