### ISSUE TITLE
Replace 'request' package since it is deprecated.

### ISSUE THREAD

**Issue by anushreemjoshi** [ibm-cloud-security/appid-serversdk-nodejs#202]
Security issue is reported for http-signature package that is used in 'request' package which is already deprecated.
Request to please replace 'request' package since it is deprecated ad update with another suitable package.

**Comment by abod-akhras** [comment]
Thank you for reporting this issue and sorry for the late reply.
The Request library has been removed completely from the package now and been replaced with GotJS
