### ISSUE TITLE
Typescript support added for appid-serversdk-nodejs

### ISSUE THREAD

**Issue by younes-io** [ibm-cloud-security/appid-serversdk-nodejs#267]
I have added a PR in DefinitelyTyped for this package to have typings : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59745 

Please, do not hesitate to contribute to enhance the typings.

**Comment by abod-akhras** [comment]
Thank you for your contribution @younes-io. We have pushed a new version of [ibmcloud-appid](https://www.npmjs.com/package/ibmcloud-appid) ([appid-serversdk-nodejs](https://github.com/ibm-cloud-security/appid-serversdk-nodejs)) version 6.3.0 !  it includes your contribution for typescript support.

**Comment by younes-io** [comment]
@abod-akhras Yes, I saw that. I started this because I didn't have any feedback back then on the official repo, so I thought maybe it could be useful to start here... Thank you for the merge :)
