### ISSUE TITLE
dependent package jsonwebtoken 8.5.1 is deprecated and having security issues

### ISSUE THREAD

**Issue by mohkhodeer** [ibm-cloud-security/appid-serversdk-nodejs#286]
ibmcloud-appid package uses  jsonwebtoken 8.5.1 which is deprecated now and having security issues
jsonwebtoken 9.0.0 is available now, any plans to update ibmcloud-appid to use the newer version of jsonwebtoken package?
Thanks

**Comment by spraju92** [comment]
Any updates on this issue? It is advised to upgrade jsonwebtoken to version 9.0.0 because it has been rated as having a High vulnerability. We cannot upgrade jsonwebtoken alone because it is an ibmcloud-appid peer dependency.
