### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [ibm-cloud-security/appid-serversdk-nodejs#67]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by motyd** [comment]
The use of ejs is in an example, and not in the core of the library. 
Users of this SDK may use any template library they wish.

I am closing this issue. If you like, you can open a PR and we'll consider it.
