### ISSUE TITLE
AttributeManager in Angular

### ISSUE THREAD

**Issue by ChristofferArnlund** [ibm-cloud-security/appid-serversdk-nodejs#70]
Hi! 

We're using App-ID on Node.js that redirects to an angular5 project. What is the best way of using the attribute manager in such a way that we can put user attribute specific logic in the angular project? Right now I'm thinking of setting up an internal endpoint to make such changes. Is this the correct way?

**Comment by motyd** [comment]
How are you using App ID in Node.JS? Are you using the WebAppStrategy?
If so then probably the best way would be to expose an endpoint on the Node side that will use the Attributes manager, and protect this endpoint with the WebAppStrategy.

**Comment by ChristofferArnlund** [comment]
Hi @motyd! Thank you for the answer!

Yes, we are currently using it together with the WebAppStrategy. I have checked other sources in Node.js & Angular Integration and it indeed seems like that's the way to go!

On another note, we are trying to run the project locally and have followed the guide and implemented the necessary steps mentioned in the guide. However, we're given an error that says that the Attribute Manager is not connected to App-id (or that parameters are missing). Is it possible to use the Attribute Manager locally, and if it is, Is there some additional steps needed to be taken in order for the AM to work properly?

**Comment by motyd** [comment]
Yes, to use the Attributes Manager locally all you need to do is to supply it with the App ID credentials for your instance as the option parameter. I am guessing you are already doing something similar for the WebAppStrategy initialization. 

Here is an example:

```
const userAttributeManager = require("bluemix-appid").UserAttributeManager;
// get those from the App ID console:
const credentials = {
    "version": 3,
    "clientId": "xxx",
    "secret": "xxx",
    "tenantId": "xxx",
    "oauthServerUrl": "https://appid-oauth.eu-gb.bluemix.net/oauth/v3/xxx",
    "profilesUrl": "https://appid-profiles.eu-gb.bluemix.net"
};

// Initialize the user attribute Manager
userAttributeManager.init(credentials);
```

**Comment by motyd** [comment]
@ChristofferArnlund did you succeed in implementing what you tried to do?
Can this issue be closed?
