### ISSUE TITLE
Missing api to get all users from appid service.

### ISSUE THREAD

**Issue by chaitanya11** [ibm-cloud-security/appid-serversdk-nodejs#93]
There is no implementation to get list of users from management api of appid service, which is mentioned [here](https://appid-management.ng.bluemix.net/swagger-ui/#!/Users/createCloudDirectoryUser).

Will this implementation comes in future releases ?

**Comment by motyd** [comment]
There are currently no plans to incorporate management operations into the SDK (other then the operations that are already included to help with workflows).
